---
# https://www.talos.dev/v1.7/kubernetes-guides/network/deploying-cilium/#method-2-helm-manifests-install
- name: Add a repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Render Cilium helm chart templates
  ansible.builtin.command: >
    helm template
      cilium
      cilium/cilium
      --version {{ talos_cilium_chart_version }}
      --namespace kube-system
      --set operator.replicas=1
      --set ipam.mode=kubernetes
      --set kubeProxyReplacement=true
      --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
      --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
      --set cgroup.autoMount.enabled=false
      --set cgroup.hostRoot=/sys/fs/cgroup
      --set k8sServiceHost={{ talos_node_ip }}
      --set k8sServicePort={{ talos_kube_api_port }}
      --set loadBalancer.acceleration=best-effort
      --set gatewayAPI.enabled=true
  # --set l2announcements.enabled=true
  register: talos_helm_template_render
  changed_when: false # because of randomly generated TLS certs
  no_log: true # contains sensitive info

- name: Write cilium template in one temporary file
  ansible.builtin.template:
    src: cilium.patch.j2
    dest: "{{ talos_config_dir }}/cilium.yaml"
    mode: "0600"
  changed_when: false # because of randomly generated TLS certs
  no_log: true # contains sensitive info
