---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create cluster
      ansible.builtin.import_role:
        name: talos
      vars:
        talos_config_dir: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/talosconfig.d"
