name: GitHub Actions

on:
  pull_request:
  push:

jobs:
  Build-Devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image
        uses: devcontainers/ci@v0.3
        with:
          imageName: "ghcr.io/${{ github.repository }}"
          cacheFrom: "ghcr.io/${{ github.repository }}"
          push: always

  Ansible-Role-Test:
    needs: Build-Devcontainer
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository }}"
    steps:
      - uses: actions/checkout@v4

      - name: run molecule
        run: molecule test

  Pre-commit-auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
